version: "3.8"

services:
  mysql:
    image: mysql:8.0.35
    container_name: crud-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: crud-db
    volumes:
      - ./.container/mysql:/var/lib/mysql